/**
 * Generates premium CSS for the Scaler clone.
 */
export function buildScalerCSS() {
  return `/* ═══════════════════════════════════════
   Scaler Clone — Premium Stylesheet
   Generated by CLI AI Agent
   ═══════════════════════════════════════ */

:root {
  --bg-primary: #0a0a14;
  --bg-secondary: #0f0f1e;
  --bg-card: #151528;
  --bg-card-hover: #1a1a35;
  --text-primary: #eaeaf0;
  --text-secondary: #8888a8;
  --accent: #5046e5;
  --accent-light: #7c6ff7;
  --accent-glow: rgba(80, 70, 229, 0.25);
  --accent-gradient: linear-gradient(135deg, #5046e5 0%, #7c3aed 50%, #a855f7 100%);
  --border: rgba(255, 255, 255, 0.06);
  --border-hover: rgba(255, 255, 255, 0.12);
  --font: 'Inter', system-ui, -apple-system, sans-serif;
  --radius: 14px;
  --radius-sm: 8px;
  --transition: 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

/* ── Reset ── */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  font-family: var(--font);
  background: var(--bg-primary);
  color: var(--text-primary);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
  overflow-x: hidden;
}
a { color: inherit; text-decoration: none; }
ul { list-style: none; }
img { max-width: 100%; display: block; }

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px;
}

/* ═══ HEADER ═══ */
#site-header {
  position: fixed;
  top: 0; left: 0; right: 0;
  z-index: 1000;
  background: rgba(10, 10, 20, 0.8);
  backdrop-filter: blur(20px) saturate(180%);
  border-bottom: 1px solid var(--border);
  transition: all var(--transition);
}
#site-header.scrolled {
  background: rgba(10, 10, 20, 0.95);
  box-shadow: 0 4px 30px rgba(0, 0, 0, 0.3);
}
.header-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 72px;
}
.logo {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 800;
  font-size: 1.4rem;
}
.logo-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  background: var(--accent-gradient);
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 900;
  color: #fff;
}
.logo-text { color: var(--text-primary); }
.main-nav {
  display: flex;
  align-items: center;
  gap: 8px;
}
.nav-links { display: flex; gap: 2px; }
.nav-link {
  padding: 8px 14px;
  border-radius: var(--radius-sm);
  font-size: 0.88rem;
  font-weight: 500;
  color: var(--text-secondary);
  transition: all var(--transition);
  white-space: nowrap;
}
.nav-link:hover {
  color: var(--text-primary);
  background: rgba(255, 255, 255, 0.05);
}
.nav-cta { display: flex; gap: 10px; margin-left: 16px; }

/* ── Buttons ── */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 10px 22px;
  border-radius: var(--radius-sm);
  font-size: 0.88rem;
  font-weight: 600;
  cursor: pointer;
  border: none;
  transition: all var(--transition);
  white-space: nowrap;
}
.btn-ghost {
  background: transparent;
  color: var(--text-secondary);
  border: 1px solid var(--border);
}
.btn-ghost:hover {
  color: var(--text-primary);
  border-color: var(--border-hover);
  background: rgba(255, 255, 255, 0.03);
}
.btn-primary-sm {
  background: var(--accent);
  color: #fff;
}
.btn-primary-sm:hover { background: var(--accent-light); transform: translateY(-1px); }
.btn-primary {
  background: var(--accent-gradient);
  color: #fff;
  padding: 14px 32px;
  font-size: 0.95rem;
  border-radius: var(--radius);
  box-shadow: 0 4px 20px var(--accent-glow);
}
.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 40px var(--accent-glow);
}
.btn-secondary {
  background: rgba(255, 255, 255, 0.05);
  color: var(--text-primary);
  border: 1px solid var(--border-hover);
  padding: 14px 32px;
  font-size: 0.95rem;
  border-radius: var(--radius);
}
.btn-secondary:hover {
  border-color: var(--accent);
  background: var(--accent-glow);
}
.btn-outline {
  background: transparent;
  color: var(--accent-light);
  border: 1px solid var(--accent);
  padding: 10px 20px;
  font-size: 0.85rem;
  border-radius: var(--radius-sm);
}
.btn-outline:hover {
  background: var(--accent-glow);
  transform: translateY(-1px);
}

/* ── Mobile Toggle ── */
.mobile-toggle {
  display: none;
  flex-direction: column;
  gap: 5px;
  background: none;
  border: none;
  cursor: pointer;
  padding: 4px;
  z-index: 1001;
}
.mobile-toggle span {
  width: 22px; height: 2px;
  background: var(--text-primary);
  border-radius: 2px;
  transition: all var(--transition);
}
.mobile-toggle.active span:nth-child(1) { transform: translateY(7px) rotate(45deg); }
.mobile-toggle.active span:nth-child(2) { opacity: 0; }
.mobile-toggle.active span:nth-child(3) { transform: translateY(-7px) rotate(-45deg); }

/* ═══ HERO ═══ */
.hero {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding-top: 72px;
  position: relative;
  overflow: hidden;
}
.hero-bg-effects {
  position: absolute;
  inset: 0;
  pointer-events: none;
  overflow: hidden;
}
.hero-glow {
  position: absolute;
  border-radius: 50%;
  filter: blur(120px);
}
.hero-glow-1 {
  top: -20%;
  right: -10%;
  width: 600px;
  height: 600px;
  background: rgba(80, 70, 229, 0.15);
  animation: float1 8s ease-in-out infinite;
}
.hero-glow-2 {
  bottom: -10%;
  left: -5%;
  width: 400px;
  height: 400px;
  background: rgba(168, 85, 247, 0.1);
  animation: float2 10s ease-in-out infinite;
}
.hero-grid-overlay {
  position: absolute;
  inset: 0;
  background-image:
    linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px),
    linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px);
  background-size: 60px 60px;
}
@keyframes float1 {
  0%, 100% { transform: translate(0, 0) scale(1); }
  50% { transform: translate(-30px, 20px) scale(1.1); }
}
@keyframes float2 {
  0%, 100% { transform: translate(0, 0) scale(1); }
  50% { transform: translate(20px, -20px) scale(1.05); }
}
.hero-inner {
  display: grid;
  grid-template-columns: 1.2fr 1fr;
  gap: 60px;
  align-items: center;
  padding: 80px 0 40px;
  position: relative;
  z-index: 1;
}
.hero-badge {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 6px 16px;
  background: var(--accent-glow);
  border: 1px solid rgba(80, 70, 229, 0.3);
  border-radius: 20px;
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--accent-light);
  margin-bottom: 24px;
}
.badge-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #22c55e;
  animation: pulse-dot 2s ease-in-out infinite;
}
@keyframes pulse-dot {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.4; }
}
.hero-headline {
  font-size: clamp(2.2rem, 4.5vw, 3.5rem);
  font-weight: 900;
  line-height: 1.1;
  letter-spacing: -1.5px;
  margin-bottom: 20px;
  background: linear-gradient(135deg, #fff 0%, #c0c0e0 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}
.hero-sub {
  font-size: 1.1rem;
  color: var(--text-secondary);
  line-height: 1.7;
  margin-bottom: 32px;
  max-width: 520px;
}
.hero-cta { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 32px; }
.hero-trust {
  display: flex;
  align-items: center;
  gap: 12px;
  font-size: 0.88rem;
  color: var(--text-secondary);
}
.trust-avatars {
  display: flex;
}
.avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.75rem;
  font-weight: 700;
  color: #fff;
  border: 2px solid var(--bg-primary);
  margin-right: -8px;
}
.trust-avatars .avatar:last-child { margin-right: 0; }
.hero-trust strong { color: var(--text-primary); }

/* Hero Visual */
.hero-visual {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
}
.hero-card-stack { position: relative; width: 100%; max-width: 400px; aspect-ratio: 1; }
.hero-graphic {
  width: 280px;
  height: 280px;
  border-radius: 50%;
  background: var(--accent-gradient);
  opacity: 0.12;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  animation: pulse-glow 4s ease-in-out infinite;
}
@keyframes pulse-glow {
  0%, 100% { transform: translate(-50%, -50%) scale(1); opacity: 0.12; }
  50% { transform: translate(-50%, -50%) scale(1.08); opacity: 0.2; }
}
.floating-card {
  position: absolute;
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 14px 20px;
  background: rgba(21, 21, 40, 0.9);
  backdrop-filter: blur(12px);
  border: 1px solid var(--border-hover);
  border-radius: var(--radius);
  font-size: 0.88rem;
  font-weight: 600;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
  animation: float-card 6s ease-in-out infinite;
}
.fc-icon { font-size: 1.2rem; }
.fc-1 { top: 15%; right: 5%; animation-delay: 0s; }
.fc-2 { top: 45%; left: 0%; animation-delay: 2s; }
.fc-3 { bottom: 15%; right: 10%; animation-delay: 4s; }
@keyframes float-card {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-10px); }
}

/* Company Bar */
.company-bar {
  padding: 40px 0;
  border-top: 1px solid var(--border);
  position: relative;
  z-index: 1;
}
.company-label {
  text-align: center;
  font-size: 0.8rem;
  color: var(--text-secondary);
  margin-bottom: 20px;
  text-transform: uppercase;
  letter-spacing: 1.5px;
}
.company-logos {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
  gap: 32px;
}
.company-logo {
  font-size: 0.95rem;
  font-weight: 700;
  color: rgba(255, 255, 255, 0.2);
  letter-spacing: 1px;
  transition: color var(--transition);
}
.company-logo:hover { color: rgba(255, 255, 255, 0.5); }

/* ═══ SECTIONS (shared) ═══ */
.section { padding: 100px 0; }
.section-header {
  text-align: center;
  max-width: 650px;
  margin: 0 auto 60px;
}
.section-tag {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 2px;
  color: var(--accent-light);
  margin-bottom: 16px;
  padding: 6px 16px;
  background: var(--accent-glow);
  border-radius: 20px;
  border: 1px solid rgba(80, 70, 229, 0.2);
}
.section-header h2 {
  font-size: clamp(1.8rem, 3vw, 2.5rem);
  font-weight: 800;
  line-height: 1.2;
  letter-spacing: -0.5px;
  margin-bottom: 16px;
}
.section-sub {
  font-size: 1rem;
  color: var(--text-secondary);
  line-height: 1.6;
}

/* ═══ WHY SCALER ═══ */
.why-section { background: var(--bg-primary); }
.why-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 24px;
}
.why-card {
  padding: 36px;
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  transition: all var(--transition);
  position: relative;
  overflow: hidden;
}
.why-card::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 2px;
  background: var(--accent-gradient);
  opacity: 0;
  transition: opacity var(--transition);
}
.why-card:hover {
  background: var(--bg-card-hover);
  border-color: var(--border-hover);
  transform: translateY(-4px);
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
}
.why-card:hover::before { opacity: 1; }
.why-icon {
  font-size: 2rem;
  margin-bottom: 16px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 56px;
  height: 56px;
  background: var(--accent-glow);
  border-radius: 12px;
}
.why-card h3 {
  font-size: 1.15rem;
  font-weight: 700;
  margin-bottom: 12px;
}
.why-card p {
  font-size: 0.9rem;
  color: var(--text-secondary);
  line-height: 1.7;
}

/* ═══ PROGRAMS ═══ */
.programs-section { background: var(--bg-secondary); }
.programs-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 24px;
}
.program-card {
  padding: 32px;
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  transition: all var(--transition);
  display: flex;
  flex-direction: column;
}
.program-card:hover {
  border-color: var(--accent);
  transform: translateY(-4px);
  box-shadow: 0 20px 60px rgba(80, 70, 229, 0.15);
}
.program-icon {
  font-size: 2rem;
  margin-bottom: 16px;
}
.program-card h3 {
  font-size: 1.1rem;
  font-weight: 700;
  margin-bottom: 8px;
  line-height: 1.3;
}
.program-rating {
  font-size: 0.8rem;
  color: var(--accent-light);
  font-weight: 600;
  margin-bottom: 12px;
}
.program-card p {
  font-size: 0.88rem;
  color: var(--text-secondary);
  line-height: 1.7;
  margin-bottom: 20px;
  flex: 1;
}
.program-card .btn-outline { align-self: flex-start; }

/* ═══ STATS ═══ */
.stats-section {
  background: var(--bg-primary);
  border-top: 1px solid var(--border);
  border-bottom: 1px solid var(--border);
}
.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 24px;
  margin-bottom: 24px;
}
.stat-card {
  text-align: center;
  padding: 36px 20px;
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  transition: all var(--transition);
}
.stat-card:hover {
  border-color: var(--accent);
  transform: translateY(-4px);
  box-shadow: 0 12px 40px var(--accent-glow);
}
.stat-value {
  font-size: 2.5rem;
  font-weight: 900;
  background: var(--accent-gradient);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  margin-bottom: 8px;
}
.stat-label {
  font-size: 0.85rem;
  color: var(--text-secondary);
  line-height: 1.5;
}
.stats-note {
  text-align: center;
  font-size: 0.8rem;
  color: var(--text-secondary);
  font-style: italic;
  margin-bottom: 24px;
}
.stats-cta { text-align: center; }

/* ═══ FOOTER ═══ */
#site-footer {
  background: var(--bg-secondary);
  border-top: 1px solid var(--border);
  padding-top: 64px;
}
.footer-inner {
  display: grid;
  grid-template-columns: 1.2fr 3fr;
  gap: 48px;
  padding-bottom: 48px;
}
.footer-brand .logo { margin-bottom: 12px; display: inline-flex; }
.footer-tagline {
  font-size: 0.88rem;
  color: var(--text-secondary);
  margin-bottom: 16px;
}
.footer-phone {
  font-size: 0.88rem;
  color: var(--text-secondary);
  transition: color var(--transition);
}
.footer-phone:hover { color: var(--accent-light); }
.footer-columns {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 32px;
}
.footer-column h4 {
  font-size: 0.8rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 1.5px;
  color: var(--text-primary);
  margin-bottom: 16px;
}
.footer-column li { margin-bottom: 10px; }
.footer-column a {
  font-size: 0.88rem;
  color: var(--text-secondary);
  transition: all var(--transition);
}
.footer-column a:hover {
  color: var(--accent-light);
  padding-left: 4px;
}
.footer-bottom {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 24px 24px;
  border-top: 1px solid var(--border);
  font-size: 0.82rem;
  color: var(--text-secondary);
}
.footer-bottom-links { display: flex; gap: 20px; }
.footer-bottom-links a {
  color: var(--text-secondary);
  transition: color var(--transition);
}
.footer-bottom-links a:hover { color: var(--accent-light); }

/* ═══ ANIMATIONS ═══ */
.fade-in {
  opacity: 0;
  transform: translateY(24px);
  transition: opacity 0.7s ease, transform 0.7s ease;
}
.fade-in.visible {
  opacity: 1;
  transform: translateY(0);
}

/* ═══ RESPONSIVE ═══ */
@media (max-width: 1024px) {
  .hero-inner { grid-template-columns: 1fr; text-align: center; }
  .hero-sub { margin: 0 auto 32px; }
  .hero-cta { justify-content: center; }
  .hero-trust { justify-content: center; }
  .hero-visual { display: none; }
  .why-grid { grid-template-columns: 1fr; }
  .programs-grid { grid-template-columns: 1fr; }
  .stats-grid { grid-template-columns: repeat(2, 1fr); }
  .footer-inner { grid-template-columns: 1fr; }
  .footer-columns { grid-template-columns: repeat(2, 1fr); }
}
@media (max-width: 768px) {
  .mobile-toggle { display: flex; }
  .main-nav {
    position: fixed;
    top: 72px; left: 0; right: 0; bottom: 0;
    flex-direction: column;
    background: rgba(10, 10, 20, 0.98);
    backdrop-filter: blur(20px);
    padding: 24px;
    transform: translateX(100%);
    transition: transform var(--transition);
    overflow-y: auto;
  }
  .main-nav.open { transform: translateX(0); }
  .nav-links { flex-direction: column; }
  .nav-link { padding: 12px 16px; font-size: 1rem; }
  .nav-cta { flex-direction: column; margin-left: 0; margin-top: 16px; }
  .hero-headline { font-size: 2rem; }
  .stats-grid { grid-template-columns: 1fr 1fr; gap: 16px; }
  .stat-value { font-size: 1.8rem; }
  .footer-columns { grid-template-columns: 1fr; }
  .footer-bottom { flex-direction: column; gap: 16px; text-align: center; }
  .company-logos { gap: 16px; }
}`;
}
