import axios from "axios";
import * as cheerio from "cheerio";
import fs from "fs";
import path from "path";
import { exec } from "child_process";
import { buildScalerHTML } from "./scaler-html.js";
import { buildScalerCSS } from "./scaler-css.js";

// ═══════════════════════════════════════════════════════
// Content Store — tools save large outputs here so the
// LLM only ever sees short summaries, never raw HTML/CSS/JS.
// ═══════════════════════════════════════════════════════
const contentStore = {};

// ─── Tool: fetchHTML ───
export async function fetchHTML({ url }) {
  try {
    const { data } = await axios.get(url, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        Accept: "text/html,application/xhtml+xml",
      },
      timeout: 15000,
    });
    const html = typeof data === "string" ? data : String(data);
    // Store full HTML internally — LLM never sees it
    contentStore.rawHTML = html;
    return `SUCCESS: Fetched ${url} (${html.length} chars). HTML stored internally. Call parseAndExtract next (no input needed).`;
  } catch (err) {
    return `ERROR: ${err.message}`;
  }
}

// ─── Tool: parseAndExtract ───
export async function parseAndExtract({ html }) {
  // Use stored HTML if available (avoids sending HTML through LLM)
  const source = html || contentStore.rawHTML || "";
  if (!source) return `ERROR: No HTML available. Call fetchHTML first.`;

  const $ = cheerio.load(source);
  $("script, style, noscript, iframe, svg, link[rel=stylesheet]").remove();

  // ── Header ──
  const headerEl = $("header").first().length ? $("header").first() : $("nav").first();
  const logo = {
    text: headerEl.find('a[class*="logo"], a:first-child, [class*="logo"]').first().text().trim() || "Scaler",
    imgUrl: headerEl.find("img").first().attr("src") || "",
  };
  const navLinks = [];
  headerEl.find("a").each((_, el) => {
    const t = $(el).text().trim();
    const h = $(el).attr("href") || "#";
    if (t && t.length < 40 && !navLinks.find((l) => l.text === t)) {
      navLinks.push({ text: t, href: h });
    }
  });

  // ── Hero ──
  const headline = $("h1").first().text().trim() || "Become the Professional Built for the Next Decade in AI.";
  const subheadline = $("h1 ~ p, h1 + p").first().text().trim() ||
    "The investment that compounds. Strong technical foundations, AI integrated at every stage, and a curriculum that evolves as the market does.";

  // ── Footer ──
  const footerEl = $("footer").first();
  const copyright = footerEl.find('[class*="copy"], p:last-child').text().trim() || `© ${new Date().getFullYear()} Scaler`;

  const extracted = {
    header: { logo, navLinks: navLinks.slice(0, 8) },
    hero: { headline, subheadline },
    footer: { copyright },
  };

  // Store for generateScalerPage
  contentStore.extractedData = extracted;

  return JSON.stringify(extracted);
}

// ─── Tool: generateScalerPage ───
export async function generateScalerPage({ data } = {}) {
  const d = data || contentStore.extractedData || {};
  const html = buildScalerHTML(d);
  contentStore.pageHTML = html;
  return `SUCCESS: Generated Scaler HTML page (${html.length} chars). Stored internally — use saveFile with content "{{html}}" to save it.`;
}

// ─── Legacy alias ───
export async function generateCleanHTML({ sections } = {}) {
  await generateScalerPage({ data: sections });
  return contentStore.pageHTML;
}

// ─── Tool: generateCSS ───
export async function generateCSS() {
  const css = buildScalerCSS();
  contentStore.pageCSS = css;
  return `SUCCESS: Generated CSS stylesheet (${css.length} chars). Stored internally — use saveFile with content "{{css}}" to save it.`;
}

// ─── Tool: generateJS ───
export async function generateJS() {
  const js = `/* ═══════════════════════════════════════
   Scaler Clone — Interactive Script
   Generated by CLI AI Agent
   ═══════════════════════════════════════ */

document.addEventListener('DOMContentLoaded', () => {
  // Mobile Menu Toggle
  const toggle = document.getElementById('menuToggle');
  const nav = document.getElementById('mainNav');
  if (toggle && nav) {
    toggle.addEventListener('click', () => {
      nav.classList.toggle('open');
      toggle.classList.toggle('active');
    });
    nav.querySelectorAll('.nav-link').forEach(link => {
      link.addEventListener('click', () => {
        nav.classList.remove('open');
        toggle.classList.remove('active');
      });
    });
  }

  // Scroll-based header styling
  const header = document.getElementById('site-header');
  if (header) {
    window.addEventListener('scroll', () => {
      header.classList.toggle('scrolled', window.scrollY > 50);
    }, { passive: true });
  }

  // Smooth scroll for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', (e) => {
      const targetId = anchor.getAttribute('href');
      if (targetId === '#') return;
      const target = document.querySelector(targetId);
      if (target) {
        e.preventDefault();
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });

  // Fade-in animations on scroll
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.1, rootMargin: '0px 0px -50px 0px' });

  document.querySelectorAll(
    '.hero-content, .hero-badge, .why-card, .program-card, .stat-card, .footer-column, .section-header'
  ).forEach((el, i) => {
    el.classList.add('fade-in');
    el.style.transitionDelay = (i % 4) * 0.1 + 's';
    observer.observe(el);
  });

  // Animated stat counters
  const statObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const el = entry.target;
        const finalText = el.textContent;
        const numMatch = finalText.match(/[\\d.]+/);
        if (numMatch) {
          const finalNum = parseFloat(numMatch[0]);
          const prefix = finalText.slice(0, finalText.indexOf(numMatch[0]));
          const suffix = finalText.slice(finalText.indexOf(numMatch[0]) + numMatch[0].length);
          let current = 0;
          const step = finalNum / 40;
          const interval = setInterval(() => {
            current += step;
            if (current >= finalNum) { current = finalNum; clearInterval(interval); }
            el.textContent = prefix + Math.round(current) + suffix;
          }, 30);
        }
        statObserver.unobserve(el);
      }
    });
  }, { threshold: 0.5 });
  document.querySelectorAll('.stat-value').forEach(el => statObserver.observe(el));

  console.log('Scaler clone loaded successfully.');
});
`;
  contentStore.pageJS = js;
  return `SUCCESS: Generated JS script (${js.length} chars). Stored internally — use saveFile with content "{{js}}" to save it.`;
}

// ─── Tool: saveFile ───
export async function saveFile({ filename, content }) {
  // Resolve content store references so LLM never handles big strings
  let resolved = content;
  if (content === "{{html}}") resolved = contentStore.pageHTML;
  else if (content === "{{css}}") resolved = contentStore.pageCSS;
  else if (content === "{{js}}") resolved = contentStore.pageJS;

  if (!resolved) return `ERROR: No content to save. Generate it first.`;

  const dir = path.dirname(filename);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filename, resolved, "utf-8");
  return `File saved: ${filename} (${resolved.length} bytes)`;
}

// ─── Tool: openInBrowser ───
export async function openInBrowser({ filepath }) {
  const abs = path.resolve(filepath);
  if (!fs.existsSync(abs)) return `ERROR: File not found: ${abs}`;
  return new Promise((resolve) => {
    exec(`start "" "${abs}"`, (err) => {
      resolve(err ? `ERROR: ${err.message}` : `Opened in browser: ${abs}`);
    });
  });
}

// ─── Tool Map ───
export const toolMap = {
  fetchHTML,
  parseAndExtract,
  generateScalerPage,
  generateCleanHTML,
  generateCSS,
  generateJS,
  saveFile,
  openInBrowser,
};
